tests = [ {'description': 'PINA: 0x00 => PORTC: 0x00 PORTB: 0x00' ,
    'steps': [ {'inputs': [('PINA',0x00)] , 'iterations': 1 } ],
    'expected': [('PORTC',0x00), ('PORTB',0x00)],
    },
     {'description': 'PINA: 0x0F => PORTC: 0xF0 PORTB:0x00',
        'steps': [ {'inputs': [('PINA',0x0F)] , 'iterations': 1 }],
        'expected': [('PORTC',0xF0),('PORTB', 0x00)],
        },
     {'description': 'PINA: 0xAD => PORTC: 0xD0 PORTB: 0A',
        'steps': [ {'inputs': [('PINA',0xAD)] , 'iterations': 1 }],
        'expected': [('PORTC',0xD0), ('PORTB',0x0A)],
        },
 {'description': 'PINA: 0x7B => PORTC: 0xB0 PORTB: 0x07',
        'steps': [ {'inputs': [('PINA',0x7B),] , 'iterations': 1 }],
        'expected': [('PORTC',0xB0),('PORTB',0x07)],
        },
{'description': 'PINA: 0xA9 => PORTC: 0x90 PORTB: 0x0A',
        'steps': [ {'inputs': [('PINA',0xA9)] , 'iterations': 1 }],
        'expected': [('PORTC',0x90), ('PORTB', 0x0A)],
        },
    ]

